// Learning content for the Learning tab. English now; Bangla translations to follow.
// Each course has lectures; each lecture has reading `body` bullets + a 10-question quiz.

export type QuizQuestion = {
  q: string;
  options: string[];
  correct: number; // index into options
  why: string; // short explanation shown after answering
};

export type Lecture = {
  title: string;
  body: string[];
  quiz: QuizQuestion[];
};

export type Course = {
  key: string;
  title: string;
  icon: string; // Ionicons glyph name
  blurb: string;
  lectures: Lecture[];
};

export const COURSES: Course[] = [
  {
    key: 'budgeting',
    title: 'Budgeting Basics',
    icon: 'wallet',
    blurb: 'Plan where your money goes and take control of every taka.',
    lectures: [
      {
        title: 'What is a budget & why it matters',
        body: [
          'A budget is a simple plan for your money: it shows what you earn and decides where each taka goes before you spend it.',
          "Budgeting isn't about restricting yourself — it's about telling your money what to do so you don't wonder where it went.",
          'Even with a small or irregular income, a budget helps you cover essentials, avoid borrowing, and slowly build savings.',
          'Reviewing your budget monthly helps you spot leaks — like too many small bazar trips or recharges — and adjust.',
        ],
        quiz: [
          { q: 'What is a budget?', options: ['A plan for how you earn and spend money', 'A type of bank loan', 'A government tax', 'A mobile recharge offer'], correct: 0, why: 'A budget is a plan that tells your money where to go.' },
          { q: 'The main purpose of budgeting is to…', options: ['Stop you from ever spending', 'Decide where money goes before you spend', 'Make you feel guilty', 'Increase your taxes'], correct: 1, why: 'Budgeting plans spending in advance.' },
          { q: 'Budgeting is most useful for people who…', options: ['Only earn a lot', 'Have any income, even small or irregular', 'Never save', "Don't use money"], correct: 1, why: 'A budget helps at every income level.' },
          { q: 'How often should you review your budget?', options: ['Never', 'Once in a lifetime', 'Regularly, e.g. monthly', 'Only when broke'], correct: 2, why: 'Regular reviews keep it accurate.' },
          { q: 'A budget helps you avoid…', options: ['Earning money', 'Unnecessary borrowing', 'Saving', 'Eating'], correct: 1, why: 'Planning reduces the need to borrow.' },
          { q: '"Telling your money what to do" means…', options: ['Spending randomly', 'Planning spending in advance', 'Hiding money', 'Lending to friends'], correct: 1, why: 'You assign a purpose before spending.' },
          { q: 'Which is a sign you need a budget?', options: ['You always know where money goes', "Money disappears and you're not sure where", 'You have huge savings', 'You never spend'], correct: 1, why: 'Untracked money is a clear signal.' },
          { q: 'A budget mainly tracks…', options: ['Your height', 'Income and expenses', 'The weather', 'Your friends'], correct: 1, why: 'It compares what comes in and goes out.' },
          { q: 'Budgeting with a small income is…', options: ['Pointless', 'Helpful for covering essentials and saving', 'Illegal', 'Only for the rich'], correct: 1, why: 'Small incomes benefit most from planning.' },
          { q: 'A "money leak" is…', options: ['A water problem', 'Small repeated spends that add up unnoticed', 'A big salary', 'A savings account'], correct: 1, why: 'Tiny leaks quietly drain your budget.' },
        ],
      },
      {
        title: 'The 50/30/20 rule for Bangladeshi incomes',
        body: [
          'The 50/30/20 rule splits your income: 50% needs, 30% wants, 20% savings and debt repayment.',
          'Needs = bazar, rent, utilities, transport. Wants = eating out, shopping, entertainment. Savings = emergency fund, goals, loan repayment.',
          "On a lower income, needs often take more than 50% — that's okay. Aim to save even 5–10% and grow it as income rises.",
          "The point isn't exact percentages — it's making sure some money always goes to savings, not just spending.",
        ],
        quiz: [
          { q: 'In 50/30/20, the 50% covers…', options: ['Needs', 'Wants', 'Savings', 'Taxes'], correct: 0, why: 'Half goes to essential needs.' },
          { q: 'The 30% is for…', options: ['Needs', 'Wants (non-essentials)', 'Savings', 'Loans'], correct: 1, why: '30% is for wants.' },
          { q: 'The 20% is for…', options: ['Needs', 'Wants', 'Savings & debt repayment', 'Entertainment'], correct: 2, why: '20% builds savings and clears debt.' },
          { q: 'Which is a "need"?', options: ['House rent', 'New phone', 'Restaurant meal', 'Movie ticket'], correct: 0, why: 'Rent is essential.' },
          { q: 'Which is a "want"?', options: ['Bazar', 'Electricity bill', 'Shopping for fun', 'Rickshaw to work'], correct: 2, why: 'Fun shopping is non-essential.' },
          { q: 'If needs exceed 50% on a low income, you should…', options: ['Give up saving', 'Still save even 5–10%', 'Borrow more', 'Ignore budgeting'], correct: 1, why: 'Saving a little still matters.' },
          { q: 'The main idea of 50/30/20 is…', options: ['Exact percentages always', 'Ensuring some money is saved', 'Spending all on wants', 'Avoiding needs'], correct: 1, why: 'It guarantees savings happen.' },
          { q: 'Paying off a loan falls under…', options: ['Needs', 'Wants', 'The 20% savings/debt', 'None'], correct: 2, why: 'Debt repayment sits in the 20%.' },
          { q: 'Saving a small percentage is…', options: ['Useless', 'A good habit that grows', 'Only for the rich', 'Illegal'], correct: 1, why: 'Habits compound over time.' },
          { q: 'As income grows, you should…', options: ['Spend it all', 'Increase the savings portion', 'Stop budgeting', 'Only buy wants'], correct: 1, why: 'Higher income means saving more.' },
        ],
      },
      {
        title: 'Tracking daily expenses',
        body: [
          'Small daily spends — bazar, rickshaw, CNG, tea, mobile recharge — feel tiny but add up to large monthly amounts.',
          "Log every expense the same day while you remember it. TakaTrack's Expenses tab makes this one tap.",
          'Tracking reveals your real habits: ৳50/day on snacks quietly becomes ৳1,500/month.',
          "You can't control what you don't measure — tracking is the first step to cutting waste.",
        ],
        quiz: [
          { q: 'Why track small daily expenses?', options: ['They add up to big amounts', "They don't matter", 'Only big buys matter', 'To waste time'], correct: 0, why: 'Small spends accumulate fast.' },
          { q: 'Best time to record an expense?', options: ['End of year', 'The same day, while you remember', 'Never', 'Only when broke'], correct: 1, why: 'Same-day logging is accurate.' },
          { q: '৳50/day on snacks is about how much per month?', options: ['~৳150', '~৳1,500', '~৳50', '~৳15'], correct: 1, why: '৳50 × 30 ≈ ৳1,500.' },
          { q: 'Which app feature logs spending fast?', options: ['Expenses tab', 'The logout button', 'The goals chart', 'None'], correct: 0, why: 'The Expenses tab is built for it.' },
          { q: '"You can\'t control what you don\'t ___"', options: ['Measure', 'Eat', 'See', 'Buy'], correct: 0, why: 'Measuring enables control.' },
          { q: 'Tracking expenses helps you…', options: ['See real spending habits', 'Earn more salary instantly', 'Avoid all taxes', 'Get a loan'], correct: 0, why: 'It exposes your true habits.' },
          { q: 'Daily items to track include…', options: ['Bazar, rickshaw, recharge', 'Only rent', 'Only salary', 'Nothing'], correct: 0, why: 'Frequent small spends matter most.' },
          { q: 'If tracking shows too much on tea/snacks, you can…', options: ['Cut back a little', 'Ignore it', 'Borrow', 'Spend more'], correct: 0, why: 'Awareness lets you adjust.' },
          { q: 'Tracking is the first step to…', options: ['Cutting waste', 'Earning interest', 'Paying tax', 'Buying gold'], correct: 0, why: 'You fix what you can see.' },
          { q: 'Same-day logging helps because…', options: ['You remember details accurately', "It's required by law", 'It earns points only', "It's slower"], correct: 0, why: 'Memory fades quickly.' },
        ],
      },
      {
        title: 'Building your first monthly budget',
        body: [
          'Start by writing your total monthly income — salary, business, freelance, and any side income.',
          'List fixed costs first (rent, utilities, transport), then variable costs (bazar, eating out), then savings.',
          "Give every taka a job until income minus all categories equals zero — this is 'zero-based budgeting'.",
          "Set realistic limits in TakaTrack's Budget tab, then track expenses against them through the month.",
        ],
        quiz: [
          { q: 'First step in building a budget?', options: ['Write your total income', 'Buy something', 'Take a loan', 'Skip savings'], correct: 0, why: 'Everything starts from income.' },
          { q: 'Fixed costs include…', options: ['Rent and utilities', 'Random shopping', 'Lottery', 'Gifts'], correct: 0, why: 'Fixed costs repeat each month.' },
          { q: '"Zero-based budgeting" means…', options: ['Income minus all categories = zero', 'Having zero money', 'No budget', 'Zero savings'], correct: 0, why: 'Every taka is assigned.' },
          { q: 'After fixed costs, you list…', options: ['Variable costs and savings', 'Nothing', 'Only wants', 'Loans only'], correct: 0, why: 'Then come variable costs and savings.' },
          { q: 'Where do you set category limits?', options: ['Budget tab', 'Logout', 'Avatar', 'Login'], correct: 0, why: 'The Budget tab holds allocations.' },
          { q: '"Give every taka a job" means…', options: ['Plan a purpose for all money', 'Spend randomly', 'Hide money', 'Lend everything'], correct: 0, why: 'No money is left unplanned.' },
          { q: 'A realistic budget…', options: ['Matches your real life and income', 'Is impossible to follow', 'Ignores income', 'Has no savings'], correct: 0, why: 'Realism keeps it usable.' },
          { q: 'Savings should be…', options: ['A planned category, not leftovers', 'Ignored', 'Only if money remains', 'Forbidden'], correct: 0, why: 'Plan savings up front.' },
          { q: 'You track expenses against your budget…', options: ['Throughout the month', 'Never', 'Only on Jan 1', 'After 10 years'], correct: 0, why: 'Ongoing tracking keeps you on plan.' },
          { q: 'Income should include…', options: ['All sources: salary, business, side income', 'Only salary', 'Only gifts', 'None'], correct: 0, why: 'Count every income source.' },
        ],
      },
    ],
  },
  {
    key: 'saving',
    title: 'Saving & Emergency Funds',
    icon: 'shield-checkmark',
    blurb: 'Build a safety net and grow steady saving habits.',
    lectures: [
      {
        title: 'Why emergency funds matter',
        body: [
          'An emergency fund is money set aside only for unexpected events: medical bills, job loss, or urgent repairs.',
          'Without it, emergencies force you to borrow at high interest or sell things you need.',
          "Keep it separate and easy to access — not invested in risky places.",
          'Even starting with ৳500–1,000 builds the habit; the goal is to never be one shock away from debt.',
        ],
        quiz: [
          { q: 'An emergency fund is for…', options: ['Unexpected events like illness or job loss', 'Daily shopping', 'Buying luxuries', 'Eating out'], correct: 0, why: 'It covers genuine emergencies.' },
          { q: 'Without one, a shock may force you to…', options: ['Borrow at high interest', 'Save more', 'Earn more', 'Relax'], correct: 0, why: 'No buffer means costly borrowing.' },
          { q: 'An emergency fund should be…', options: ['Easy to access', 'Locked for 10 years', 'Spent on wants', 'In risky stocks'], correct: 0, why: 'You need it quickly in a crisis.' },
          { q: 'A good starting amount is…', options: ['Even ৳500–1,000', 'At least ৳10 lakh first', 'Nothing', 'Only crores'], correct: 0, why: 'Start small and build up.' },
          { q: 'Which is a real emergency?', options: ['Medical bill', 'New phone for style', 'Festival shopping', 'Eating out'], correct: 0, why: 'Medical needs are true emergencies.' },
          { q: 'Emergency money should be kept…', options: ['Separate from daily spending', 'Mixed with daily cash', 'In risky shares', 'Lent to friends'], correct: 0, why: 'Separation prevents accidental spending.' },
          { q: 'The goal of an emergency fund is…', options: ['To avoid being one shock away from debt', 'To get rich quick', 'To impress people', 'To pay tax'], correct: 0, why: 'It is a safety buffer.' },
          { q: 'Using it for shopping is…', options: ['A misuse of it', 'Smart', 'Required', 'Recommended'], correct: 0, why: 'Reserve it for emergencies only.' },
          { q: 'Emergency funds reduce reliance on…', options: ['High-interest loans', 'Your salary', 'Family', 'Savings'], correct: 0, why: 'They replace costly borrowing.' },
          { q: 'Starting small is…', options: ['Still worthwhile', 'Pointless', 'Illegal', 'Only for the rich'], correct: 0, why: 'Any start builds the habit.' },
        ],
      },
      {
        title: 'How much to save (3–6 months)',
        body: [
          'A common target is 3–6 months of essential expenses — not income. Focus on what you must spend to live.',
          'Calculate monthly essentials (rent, food, utilities, transport) and multiply by 3 to 6.',
          'If your income is irregular (freelance, business), aim for the higher end — 6 months — for safety.',
          "Build it gradually: start with 1 month, then grow. Don't wait until you can save it all at once.",
        ],
        quiz: [
          { q: 'Emergency fund target is usually…', options: ['3–6 months of essential expenses', '3–6 years of income', '1 day', '10 years'], correct: 0, why: '3–6 months of essentials is standard.' },
          { q: 'It is calculated based on…', options: ['Essential expenses', 'Your wants', "Friends' incomes", 'Lottery'], correct: 0, why: 'Base it on essential costs.' },
          { q: 'Irregular income earners should aim for…', options: ['The higher end (6 months)', 'Zero', '1 week', 'Nothing'], correct: 0, why: 'More buffer covers income gaps.' },
          { q: 'To find the target, multiply monthly essentials by…', options: ['3 to 6', '100', '0', '1000'], correct: 0, why: '3–6× essentials.' },
          { q: 'Essentials include…', options: ['Rent, food, utilities', 'Movie tickets', 'Gold jewelry', 'Daily eating out'], correct: 0, why: 'Only must-have costs.' },
          { q: 'The best way to build it is…', options: ['Gradually, starting with 1 month', 'All at once or never', 'By borrowing', 'By gambling'], correct: 0, why: 'Steady steps work best.' },
          { q: "It's based on expenses, not…", options: ['Income', 'Food', 'Rent', 'Time'], correct: 0, why: 'Expenses, not income, set the size.' },
          { q: 'If monthly essentials are ৳20,000, a 3-month fund is…', options: ['৳60,000', '৳20,000', '৳6,000', '৳600'], correct: 0, why: '20,000 × 3 = 60,000.' },
          { q: 'Waiting to save it all at once is…', options: ['A mistake; start small', 'The only way', 'Smart', 'Required'], correct: 0, why: 'Starting small beats waiting.' },
          { q: 'A 6-month fund suits income that is…', options: ['Irregular', 'Fixed and stable only', 'Very high only', 'Zero'], correct: 0, why: 'Irregular income needs more cushion.' },
        ],
      },
      {
        title: 'Saving tools in Bangladesh',
        body: [
          'bKash and Nagad offer savings features and let you store money safely on your phone, away from cash in hand.',
          'A bank DPS (Deposit Pension Scheme) lets you save a fixed amount monthly and earn interest over years.',
          'A Fixed Deposit (FDR) locks a lump sum for a term at a higher interest rate.',
          'Choose by access need: keep emergency money easy to withdraw; lock long-term savings in DPS or FDR.',
        ],
        quiz: [
          { q: 'A DPS is a…', options: ['Monthly savings scheme at a bank', 'Mobile game', 'Type of loan', 'Tax'], correct: 0, why: 'DPS = monthly deposit savings.' },
          { q: 'bKash and Nagad let you…', options: ['Store and save money on your phone', 'Only make calls', 'Avoid all fees', 'Print money'], correct: 0, why: 'MFS stores money digitally.' },
          { q: 'An FDR locks…', options: ['A lump sum for a fixed term', 'Your phone', 'Your salary forever', 'Nothing'], correct: 0, why: 'FDR ties up a lump sum for a term.' },
          { q: 'Emergency money is best kept…', options: ['Easy to withdraw', 'Locked for 10 years', 'In a risky business', 'Hidden only'], correct: 0, why: 'You may need it any time.' },
          { q: 'DPS is good for…', options: ['Disciplined monthly saving', 'Daily spending', 'Gambling', 'Quick loans'], correct: 0, why: 'It enforces regular saving.' },
          { q: 'An FDR usually offers ___ than a regular account.', options: ['Higher interest', 'Lower interest', 'No interest', 'A loan'], correct: 0, why: 'Locked terms pay more interest.' },
          { q: 'Which suits long-term, locked savings?', options: ['DPS or FDR', 'Cash under the bed', 'Daily wallet', 'Spending'], correct: 0, why: 'DPS/FDR are for the long term.' },
          { q: 'MFS like bKash help keep savings…', options: ['Separate from cash in hand', 'Mixed with daily cash', 'Unsafe', 'Hidden from yourself'], correct: 0, why: 'Separation curbs spending.' },
          { q: 'Choosing a tool depends on…', options: ['How soon you need access', 'Your favorite color', 'The weather', 'Your height'], correct: 0, why: 'Access need drives the choice.' },
          { q: '"DPS" stands for…', options: ['Deposit Pension Scheme', 'Daily Payment System', 'Digital Phone Saver', 'Debt Payment Scheme'], correct: 0, why: 'Deposit Pension Scheme.' },
        ],
      },
      {
        title: 'Building saving habits',
        body: [
          "'Pay yourself first' means you save a set amount as soon as income arrives — before spending on anything else.",
          "Automate it if possible (standing instruction, auto-transfer) so saving isn't a choice you make each time.",
          'Micro-saving — putting away small amounts like ৳20–50 regularly — adds up and builds the habit.',
          'Treat savings like a fixed bill you must pay; consistency matters more than the amount.',
        ],
        quiz: [
          { q: '"Pay yourself first" means…', options: ['Save before spending', 'Spend before saving', 'Never save', 'Pay others first'], correct: 0, why: 'Save first, spend what remains.' },
          { q: 'Automating savings helps because…', options: ["Saving isn't a choice each time", "It's slower", 'It costs more', "It's risky"], correct: 0, why: 'Automation removes temptation.' },
          { q: 'Micro-saving means…', options: ['Saving small amounts regularly', 'Saving only crores', 'Never saving', 'Borrowing'], correct: 0, why: 'Small, frequent saving builds up.' },
          { q: 'The most important factor in saving is…', options: ['Consistency', 'The exact amount', 'Luck', 'Income size only'], correct: 0, why: 'Regularity beats size.' },
          { q: 'You should treat savings like…', options: ['A fixed bill to pay', 'Leftover money only', 'Optional', 'A loan'], correct: 0, why: 'Make it non-negotiable.' },
          { q: 'Saving ৳20–50 regularly is…', options: ['Worthwhile over time', 'Useless', 'Only for kids', 'Illegal'], correct: 0, why: 'Small amounts compound.' },
          { q: '"Pay yourself first" happens…', options: ['As soon as income arrives', 'Only at year-end', 'After all spending', 'Never'], correct: 0, why: 'Save the moment money comes in.' },
          { q: 'A standing instruction helps you…', options: ['Save automatically', 'Spend more', 'Avoid banks', 'Earn salary'], correct: 0, why: 'Auto-transfers enforce saving.' },
          { q: 'If you save only "leftovers", usually…', options: ['Little or nothing is left', 'You save the most', "It's the best method", 'You get rich'], correct: 0, why: 'Leftovers rarely remain.' },
          { q: 'Building a saving habit is mostly about…', options: ['Regularity', 'One big deposit', 'Luck', 'Borrowing'], correct: 0, why: 'Consistency is everything.' },
        ],
      },
    ],
  },
  {
    key: 'spending',
    title: 'Smart Spending & Avoiding Debt Traps',
    icon: 'card',
    blurb: 'Spend wisely, understand loans, and dodge debt traps.',
    lectures: [
      {
        title: 'Good debt vs bad debt',
        body: [
          'Good debt helps you build wealth or income — like a loan for education, a business, or productive assets.',
          'Bad debt funds things that lose value or get consumed — luxury shopping, gadgets you can\'t afford, or daily expenses.',
          'Even good debt is only good if repayments fit your budget; too much of any debt is risky.',
          'Before borrowing, ask: will this increase my future income, or just my spending today?',
        ],
        quiz: [
          { q: 'Good debt usually funds…', options: ['Education or a business', 'Luxury shopping', 'Daily snacks', 'A festival'], correct: 0, why: 'It builds future income or wealth.' },
          { q: 'Bad debt funds…', options: ['Things that lose value or get consumed', 'Income-producing assets', 'Skills', 'A business'], correct: 0, why: 'It pays for things that fade.' },
          { q: 'Even good debt is only good if…', options: ['Repayments fit your budget', "It's very large", 'You ignore it', "It's interest-free always"], correct: 0, why: 'Affordable repayment matters.' },
          { q: 'Before borrowing, ask whether it will…', options: ['Increase future income', 'Impress neighbors', 'Be fun', 'Cost nothing'], correct: 0, why: 'Productive borrowing pays off.' },
          { q: 'Borrowing for a course that boosts earnings is…', options: ['Potentially good debt', 'Always bad', 'Illegal', 'Pointless'], correct: 0, why: 'It can raise your income.' },
          { q: "Borrowing for a phone you can't afford is…", options: ['Bad debt', 'Good debt', 'Smart', 'Free'], correct: 0, why: 'It funds consumption you can\'t support.' },
          { q: 'Too much of any debt is…', options: ['Risky', 'Always fine', 'Recommended', 'Required'], correct: 0, why: 'Excess debt is dangerous.' },
          { q: 'Good debt helps you…', options: ['Build wealth or income', 'Lose money', 'Waste time', 'Avoid work'], correct: 0, why: 'It is an investment in your future.' },
          { q: 'A key question before a loan is…', options: ['Income, or just spending?', 'What color is it?', 'Who else has one?', 'Is it shiny?'], correct: 0, why: 'Purpose decides good vs bad.' },
          { q: 'Using a loan for daily expenses is usually…', options: ['A warning sign (bad debt)', 'Healthy', 'Recommended', 'Free money'], correct: 0, why: 'Borrowing for daily costs signals trouble.' },
        ],
      },
      {
        title: 'Understanding EMI and interest costs',
        body: [
          'EMI (Equated Monthly Installment) is the fixed amount you repay each month on a loan, including interest.',
          'A longer loan term means smaller EMIs but more total interest paid over time.',
          'Always look at the total cost (price + total interest), not just the monthly EMI, which can hide how much extra you pay.',
          'Compare the interest rate across lenders; a small rate difference adds up to large amounts on big loans.',
        ],
        quiz: [
          { q: 'EMI stands for…', options: ['Equated Monthly Installment', 'Easy Money Idea', 'Extra Monthly Income', 'Emergency Money'], correct: 0, why: 'Equated Monthly Installment.' },
          { q: 'An EMI includes…', options: ['Principal and interest', 'Only principal', 'Only fees', 'Nothing'], correct: 0, why: 'Each EMI pays both.' },
          { q: 'A longer loan term usually means…', options: ['Smaller EMI but more total interest', 'Less total interest', 'No interest', 'Higher EMI'], correct: 0, why: 'You pay longer, so more interest.' },
          { q: 'You should focus on…', options: ['Total cost, not just monthly EMI', 'Only the EMI', 'The color', "The lender's name"], correct: 0, why: 'Total repayment is what matters.' },
          { q: 'A low monthly EMI can hide…', options: ['High total interest over time', 'Free money', 'Lower cost always', 'Nothing'], correct: 0, why: 'Small EMIs can mean a long, costly loan.' },
          { q: 'Comparing lenders, you check the…', options: ['Interest rate (APR)', 'Office decor', 'Staff uniform', 'Logo'], correct: 0, why: 'The rate drives the cost.' },
          { q: 'On a big loan, a small rate difference…', options: ['Adds up to a lot', 'Means nothing', 'Is illegal', 'Lowers principal'], correct: 0, why: 'Small rates, big amounts, big totals.' },
          { q: 'Total loan cost =', options: ['Price + total interest', 'Price only', 'Interest only', 'EMI only'], correct: 0, why: 'Add interest to the price.' },
          { q: 'Extending the term to lower the EMI usually…', options: ['Raises total interest', 'Lowers total cost', 'Removes interest', 'Saves money'], correct: 0, why: 'Longer terms cost more overall.' },
          { q: 'The smart borrower compares…', options: ['Total repayment across options', 'Only EMI size', 'Only loan length', 'Nothing'], correct: 0, why: 'Compare the full repayment.' },
        ],
      },
      {
        title: 'Credit card pitfalls',
        body: [
          "Paying only the 'minimum due' keeps you in debt and piles very high interest on the rest.",
          "Credit card interest (often 25–40% per year) starts when you don't pay the full balance by the due date.",
          'Cash advances on cards usually have extra fees and interest from day one — avoid them.',
          'Use a card as a tool: pay the full statement balance every month, and never spend more than you can repay.',
        ],
        quiz: [
          { q: 'Paying only the minimum due means…', options: ['You stay in debt with high interest', "You're debt-free", 'No interest', 'Free money'], correct: 0, why: 'The rest keeps charging interest.' },
          { q: 'Credit card interest is typically…', options: ['Very high (25–40%/yr)', 'Zero', 'The lowest', 'Non-existent'], correct: 0, why: 'Card rates are among the highest.' },
          { q: 'To avoid card interest, you should…', options: ['Pay the full balance by due date', 'Pay minimum only', 'Never pay', 'Pay late'], correct: 0, why: 'Full payment avoids interest.' },
          { q: 'Cash advances usually have…', options: ['Extra fees and immediate interest', 'No cost', 'Rewards', 'Lower rates'], correct: 0, why: 'They charge from day one.' },
          { q: 'A credit card is best used as…', options: ['A tool you fully repay monthly', 'Free money', 'Extra income', 'A savings account'], correct: 0, why: 'Repay in full, use as a tool.' },
          { q: 'Interest starts when you…', options: ["Don't pay the full balance by due date", 'Pay in full', 'Use it once', 'Cut the card'], correct: 0, why: 'Carrying a balance triggers interest.' },
          { q: 'Spending more than you can repay leads to…', options: ['A debt trap', 'Wealth', 'Rewards', 'Savings'], correct: 0, why: 'Overspending traps you in debt.' },
          { q: "The 'minimum due' is designed to…", options: ['Keep you paying interest longer', 'Clear your debt fast', 'Help you save', 'Be free'], correct: 0, why: 'It maximizes interest collected.' },
          { q: 'Best habit with a credit card?', options: ['Pay full statement each month', 'Pay minimum', 'Max it out', 'Ignore the bill'], correct: 0, why: 'Full monthly payment is ideal.' },
          { q: 'Cash advances should generally be…', options: ['Avoided', 'Used daily', 'Maximized', 'Free'], correct: 0, why: 'They are costly — avoid them.' },
        ],
      },
      {
        title: 'Avoiding high-interest informal lending',
        body: [
          'Informal lenders (mohajon/moneylenders) often charge extreme interest that traps borrowers in a cycle of debt.',
          'Their loans are easy and fast, but the real cost is far higher than banks, MFS, or cooperatives.',
          'Before borrowing informally, explore alternatives: an emergency fund, family help, MFS loans, NGO/microfinance, or banks.',
          "If you must borrow, get the terms clearly, know the total repayment, and avoid 'rolling over' loans that grow each cycle.",
        ],
        quiz: [
          { q: 'Informal lenders (mohajon) often charge…', options: ['Extreme, trapping interest', 'The lowest rates', 'No interest', 'Government rates'], correct: 0, why: 'Their rates can be crippling.' },
          { q: 'Their loans attract people because they are…', options: ['Easy and fast', 'Cheap', 'Interest-free', 'Safe'], correct: 0, why: 'Speed hides the high cost.' },
          { q: 'The real cost of informal loans is usually…', options: ['Far higher than banks/MFS', 'Lower', 'Zero', 'Fixed by law'], correct: 0, why: 'They cost much more than formal options.' },
          { q: 'Better alternatives include…', options: ['Emergency fund, MFS, microfinance', 'Only mohajon', 'Gambling', 'Ignoring the need'], correct: 0, why: 'Cheaper, safer options exist.' },
          { q: '"Rolling over" a loan means…', options: ['It grows each cycle', 'It disappears', "It's repaid", "It's free"], correct: 0, why: 'New loans pile onto old debt.' },
          { q: 'Best protection against needing such loans?', options: ['An emergency fund', 'More mohajon loans', 'Spending more', 'Nothing'], correct: 0, why: 'A buffer removes the need.' },
          { q: 'Before borrowing informally, you should…', options: ['Explore cheaper alternatives', 'Sign immediately', 'Borrow the max', 'Tell no one'], correct: 0, why: 'Check safer options first.' },
          { q: 'If you must borrow, you should know the…', options: ['Total repayment and terms', "Lender's mood", 'Nothing', 'Only the cash amount'], correct: 0, why: 'Understand the full cost.' },
          { q: 'A debt cycle happens when…', options: ['New loans repay old ones repeatedly', 'You save', 'You repay fully', 'You earn more'], correct: 0, why: 'Borrowing to repay never ends.' },
          { q: 'Microfinance/NGO loans are generally ___ than mohajon.', options: ['Cheaper and safer', 'More expensive', 'Illegal', 'The same'], correct: 0, why: 'They are usually far cheaper.' },
        ],
      },
    ],
  },
  {
    key: 'mfs',
    title: 'Mobile Financial Services (MFS) Literacy',
    icon: 'phone-portrait',
    blurb: 'Use bKash, Nagad & Rocket smartly and safely.',
    lectures: [
      {
        title: 'How bKash/Nagad/Rocket work',
        body: [
          'Mobile Financial Services (MFS) like bKash, Nagad and Rocket store money in a digital wallet linked to your phone number.',
          'You add money (cash-in) at an agent or from a bank/card, and withdraw (cash-out) at agents — each wallet is secured by a secret PIN.',
          'You can send money, pay bills, recharge, and buy from merchants directly from the app or USSD code.',
          'Your PIN is like a key — never share it; agents and companies will never need it from you.',
        ],
        quiz: [
          { q: 'MFS like bKash store your money in a…', options: ['Digital wallet linked to your phone', 'Physical safe', 'Bank branch only', 'SIM card chip'], correct: 0, why: 'Money sits in a phone-linked wallet.' },
          { q: 'Adding money to your wallet is called…', options: ['Cash-in', 'Cash-out', 'Cash-burn', 'Top-down'], correct: 0, why: 'Depositing = cash-in.' },
          { q: 'Withdrawing money is called…', options: ['Cash-out', 'Cash-in', 'Deposit', 'Refund'], correct: 0, why: 'Taking money out = cash-out.' },
          { q: 'Your wallet is secured by a…', options: ['Secret PIN', 'Public number', 'Photo', 'Nothing'], correct: 0, why: 'A PIN protects your wallet.' },
          { q: 'You should share your PIN with…', options: ['No one', 'Agents', 'Callers', 'Friends'], correct: 0, why: 'Never share your PIN.' },
          { q: 'With MFS you can…', options: ['Send money, pay bills, recharge', 'Only call', 'Only text', 'Nothing'], correct: 0, why: 'MFS does many money tasks.' },
          { q: 'Rocket is a service of…', options: ['A bank (Dutch-Bangla)', 'A foreign app', 'A grocery store', 'None'], correct: 0, why: 'Rocket is Dutch-Bangla Bank\'s MFS.' },
          { q: 'Cash-in is usually done at…', options: ['An agent or from a bank/card', 'The post office', 'A restaurant', 'Nowhere'], correct: 0, why: 'Agents and bank/card add money.' },
          { q: 'A genuine company will ask for your PIN…', options: ['Never', 'Always', 'Sometimes', 'Daily'], correct: 0, why: 'Real companies never ask for it.' },
          { q: 'Your wallet is linked to your…', options: ['Phone number', 'Address', 'Passport', 'Email'], correct: 0, why: 'The wallet ties to your number.' },
        ],
      },
      {
        title: 'Transaction fees & how to minimize them',
        body: [
          'Most fees come from cash-out; cash-in is generally free.',
          'Using the app (instead of USSD) and registered/priority numbers usually gives lower cash-out rates.',
          'Paying merchants and bills directly is often free — so spending from your wallet beats cashing out then paying.',
          'Plan withdrawals: avoid many tiny cash-outs; keep money in the wallet and pay digitally when you can.',
        ],
        quiz: [
          { q: 'Most MFS fees come from…', options: ['Cash-out', 'Cash-in', 'Receiving money', 'Checking balance'], correct: 0, why: 'Cash-out carries the main fee.' },
          { q: 'Cash-in is usually…', options: ['Free', 'Very expensive', 'Banned', 'Taxed heavily'], correct: 0, why: 'Adding money is normally free.' },
          { q: 'To lower cash-out fees, use…', options: ['The app & registered numbers', 'Random agents always', 'USSD only', 'Nothing'], correct: 0, why: 'App + priority numbers cost less.' },
          { q: 'Paying a merchant from your wallet is often…', options: ['Free or cheaper than cashing out', 'Always costly', 'Impossible', 'Illegal'], correct: 0, why: 'Merchant payment avoids cash-out fees.' },
          { q: 'A good habit is to…', options: ['Pay bills/merchants digitally instead of cashing out', 'Cash out everything daily', 'Avoid the app', 'Share your PIN'], correct: 0, why: 'Spend digitally to skip fees.' },
          { q: 'Many tiny cash-outs tend to…', options: ['Add up in fees', 'Save money', 'Be free', 'Earn interest'], correct: 0, why: 'Frequent withdrawals pile up fees.' },
          { q: 'Checking your balance usually…', options: ['Costs little or nothing', 'Costs a lot', 'Is banned', 'Needs an agent'], correct: 0, why: 'Balance checks are cheap/free.' },
          { q: 'Keeping money in your wallet lets you…', options: ['Pay digitally and skip cash-out fees', 'Earn no benefit', 'Lose it', 'Pay more'], correct: 0, why: 'Digital spending avoids cash-out.' },
          { q: 'Where can you often pay with no/low fee?', options: ['Merchant payment & bill pay', 'Agent cash-out', 'ATM only', 'Nowhere'], correct: 0, why: 'Payments are often free.' },
          { q: 'Before cashing out, ask…', options: ['Can I just pay digitally instead?', "What's the agent's name?", 'Is it raining?', 'None'], correct: 0, why: 'Digital payment may avoid the fee.' },
        ],
      },
      {
        title: 'Safety — avoiding fraud and scams',
        body: [
          'Fraudsters call or text pretending to be from bKash/Nagad, often saying your account is blocked or you won a prize.',
          'They try to make you panic and share your PIN or OTP, or to "send money to verify" — never do this.',
          'No real company or agent ever needs your PIN or OTP; they are for you alone.',
          'If in doubt, hang up and contact the official helpline or app; never act on a number a caller gives you.',
        ],
        quiz: [
          { q: 'A common scam pretends to be…', options: ['From bKash/Nagad support', 'Your school', 'A doctor', 'Your boss'], correct: 0, why: 'Scammers fake support calls.' },
          { q: 'Scammers try to make you feel…', options: ['Panic or excitement', 'Calm', 'Bored', 'Sleepy'], correct: 0, why: 'Pressure clouds judgment.' },
          { q: 'You should share your OTP/PIN with…', options: ['No one, ever', 'The caller', 'The agent', 'Anyone polite'], correct: 0, why: 'OTP/PIN are private.' },
          { q: '"Send money to verify your account" is…', options: ['A scam', 'Normal', 'Required', 'Safe'], correct: 0, why: 'No one verifies by taking money.' },
          { q: 'If a caller asks for your PIN to give a prize, you…', options: ['Refuse and hang up', 'Share it', 'Send money', 'Trust them'], correct: 0, why: 'Refuse — it\'s a scam.' },
          { q: 'A real company needs your PIN…', options: ['Never', 'Always', 'At night', 'On holidays'], correct: 0, why: 'Genuine firms never need it.' },
          { q: 'If unsure, you should…', options: ['Contact the official helpline/app yourself', 'Call the scammer\'s number', 'Comply', 'Send money'], correct: 0, why: 'Verify through official channels.' },
          { q: 'An OTP is meant for…', options: ['Only you', 'Sharing', 'Agents', 'The caller'], correct: 0, why: 'OTPs are for you alone.' },
          { q: 'Urgency and pressure usually signal…', options: ['A possible scam', 'A real offer', 'Good luck', 'A bank holiday'], correct: 0, why: 'Rush tactics flag fraud.' },
          { q: 'The safest response to a suspicious money request is…', options: ['Stop and verify independently', 'Act fast', 'Pay first', 'Share details'], correct: 0, why: 'Pause and check first.' },
        ],
      },
      {
        title: 'Using MFS for savings and bill payments',
        body: [
          'MFS apps can pay utility bills (electricity, gas, water), tuition, and more — often free and instant.',
          'Some MFS offer savings features (like bKash Savings / DPS partnerships) that auto-save small amounts and earn profit.',
          'Auto-pay and reminders help you avoid late fees on bills.',
          'Keeping a separate savings feature for goals helps you avoid spending that money.',
        ],
        quiz: [
          { q: 'MFS apps can pay…', options: ['Utility bills, tuition, etc.', 'Only phone calls', 'Nothing', 'Only taxes'], correct: 0, why: 'They handle many bill types.' },
          { q: 'Bill payment via MFS is often…', options: ['Free and instant', 'Slow and costly', 'Impossible', 'Banned'], correct: 0, why: 'Bill pay is quick and cheap.' },
          { q: 'Some MFS offer…', options: ['Savings features that earn profit', 'Free cars', 'Loans only', 'Nothing'], correct: 0, why: 'Built-in savings options exist.' },
          { q: 'Auto-pay helps you avoid…', options: ['Late fees', 'Saving', 'Earning', 'Bills entirely'], correct: 0, why: 'It pays on time automatically.' },
          { q: 'A savings feature in MFS can…', options: ['Auto-save small amounts', 'Spend your money', 'Cost a fortune', 'Do nothing'], correct: 0, why: 'It sets aside money for you.' },
          { q: 'Keeping savings separate helps you…', options: ['Avoid spending it', 'Lose it', 'Pay more fees', 'Forget goals'], correct: 0, why: 'Separation protects savings.' },
          { q: 'Paying bills on time avoids…', options: ['Penalties and disconnection', 'Rewards', 'Savings', 'Profit'], correct: 0, why: 'On-time payment avoids penalties.' },
          { q: 'MFS bill pay is convenient because it\'s…', options: ['Done from your phone anytime', 'Only at offices', 'Once a year', 'Cash only'], correct: 0, why: 'Pay anytime from your phone.' },
          { q: 'Using MFS savings builds…', options: ['A saving habit', 'Debt', 'Fees', 'Nothing'], correct: 0, why: 'Regular auto-saving builds habit.' },
          { q: 'Reminders in MFS apps help with…', options: ['Paying on time', 'Spending more', 'Forgetting', 'Borrowing'], correct: 0, why: 'Reminders keep bills on track.' },
        ],
      },
    ],
  },
  {
    key: 'income',
    title: 'Income, Side Hustles & Earning More',
    icon: 'briefcase',
    blurb: 'Grow your income and manage gig/freelance earnings.',
    lectures: [
      {
        title: 'Understanding freelancing/gig income in Bangladesh',
        body: [
          'Freelancing and gig work (online services, ride-sharing, delivery, tutoring) let you earn beyond a fixed salary.',
          'Income is often irregular and per-project, so it can vary month to month.',
          'Many freelancers earn in foreign currency via platforms; payments come through banks, MFS, or services like Payoneer.',
          'Treat freelancing like a business: track income, expenses, and set aside money for lean months and taxes.',
        ],
        quiz: [
          { q: 'Gig/freelance work lets you…', options: ['Earn beyond a fixed salary', 'Only spend', 'Avoid all work', 'Get a pension'], correct: 0, why: 'It adds income beyond a salary.' },
          { q: 'Freelance income is often…', options: ['Irregular and per-project', 'Fixed monthly', 'Guaranteed', 'Tax-free always'], correct: 0, why: 'It varies by project.' },
          { q: 'Examples of gig work include…', options: ['Online services, delivery, tutoring', 'Only office jobs', 'Only farming', 'None'], correct: 0, why: 'Gig work spans many tasks.' },
          { q: 'Foreign-currency freelance payments may come via…', options: ['Banks, MFS, Payoneer', 'Only cash', 'The post', 'Never'], correct: 0, why: 'Several channels move the money.' },
          { q: 'You should treat freelancing like…', options: ['A business', 'A hobby only', 'A lottery', 'A loan'], correct: 0, why: 'Run it with business discipline.' },
          { q: 'Because income varies, you should…', options: ['Set aside money for lean months', 'Spend it all fast', 'Ignore budgeting', 'Borrow always'], correct: 0, why: 'Save for the slow months.' },
          { q: 'Tracking income and expenses helps you…', options: ['Understand your real earnings', 'Waste time', 'Avoid clients', 'Lose money'], correct: 0, why: 'Records reveal true profit.' },
          { q: 'Irregular income means some months are…', options: ['Higher and some lower', 'Always equal', 'Always zero', 'Always high'], correct: 0, why: 'Earnings rise and fall.' },
          { q: 'A wise freelancer saves for…', options: ['Taxes and slow months', 'Nothing', 'Only fun', 'Loans'], correct: 0, why: 'Plan for tax and lean times.' },
          { q: 'Gig income usually depends on…', options: ['Projects/work completed', 'A fixed contract', 'Luck only', 'Your age'], correct: 0, why: 'You earn per work done.' },
        ],
      },
      {
        title: 'Basic tax awareness for self-employed people',
        body: [
          'In Bangladesh, individuals earning above the tax-free threshold must file an income tax return with the NBR.',
          'Self-employed people and freelancers report their own income — no employer deducts it for them.',
          'Keep records of income and business expenses; legitimate expenses can reduce taxable income.',
          'A TIN (Taxpayer Identification Number) is needed for many services; filing on time avoids penalties.',
        ],
        quiz: [
          { q: 'Income tax in Bangladesh is collected by the…', options: ['NBR', 'bKash', 'DSE', 'A bank'], correct: 0, why: 'The NBR handles income tax.' },
          { q: 'Self-employed people report their income…', options: ['Themselves', 'Via an employer', 'Never', 'Through friends'], correct: 0, why: 'No employer does it for them.' },
          { q: '"TIN" stands for…', options: ['Taxpayer Identification Number', 'Total Income Note', 'Transfer ID Number', 'Tax-free Income Note'], correct: 0, why: 'Taxpayer Identification Number.' },
          { q: 'You owe income tax when income is…', options: ['Above the tax-free threshold', 'Always, from taka 1', 'Never', 'Only if salaried'], correct: 0, why: 'Tax applies above the threshold.' },
          { q: 'Keeping expense records can…', options: ['Reduce taxable income', 'Increase tax', 'Do nothing', 'Be illegal'], correct: 0, why: 'Valid expenses lower taxable income.' },
          { q: 'Filing your return on time avoids…', options: ['Penalties', 'Rewards', 'Savings', 'Profit'], correct: 0, why: 'Late filing brings penalties.' },
          { q: 'For freelancers, tax is not auto-deducted, so you must…', options: ['Track and report yourself', 'Wait for an employer', 'Ignore it', 'Hope'], correct: 0, why: 'You self-report your income.' },
          { q: 'A TIN is often required for…', options: ['Many official/financial services', 'Nothing', 'Only travel', 'Only shopping'], correct: 0, why: 'Many services need a TIN.' },
          { q: 'Legitimate business expenses are…', options: ['Deductible from income', 'Always ignored', 'Taxed extra', 'Illegal'], correct: 0, why: 'They reduce taxable income.' },
          { q: 'A good tax habit for the self-employed is…', options: ['Keep records year-round', 'Guess at year-end', 'Avoid records', 'File late'], correct: 0, why: 'Year-round records make filing easy.' },
        ],
      },
      {
        title: 'Pricing your skills/services',
        body: [
          'Price based on the value you deliver and the market rate, not just the hours you spend.',
          'Research what others charge for similar work, and factor in your skill level, costs, and time.',
          'Underpricing to win clients can trap you in low-value work; charging fairly attracts serious clients.',
          'Be clear on scope: define what is included so you can charge extra for additional work.',
        ],
        quiz: [
          { q: 'You should price based on…', options: ['Value delivered and market rate', 'Random guessing', 'The lowest possible', 'Your mood'], correct: 0, why: 'Value and market set the price.' },
          { q: 'Before setting a price, you should…', options: ['Research market rates', 'Ignore competitors', 'Charge nothing', 'Guess'], correct: 0, why: 'Know the going rate first.' },
          { q: 'Constantly underpricing can…', options: ['Trap you in low-value work', 'Make you rich fast', 'Attract great clients', 'Raise your rate'], correct: 0, why: 'Too-low prices keep you stuck.' },
          { q: 'Charging fairly tends to…', options: ['Attract serious clients', 'Scare everyone', 'Be illegal', 'Lower quality'], correct: 0, why: 'Fair prices draw real clients.' },
          { q: 'Defining scope helps you…', options: ['Charge extra for added work', 'Work for free', 'Confuse clients', 'Lose money'], correct: 0, why: 'Clear scope justifies extra charges.' },
          { q: 'Your price should factor in…', options: ['Skill, costs, and time', 'Only luck', 'Nothing', 'The weather'], correct: 0, why: 'Account for skill, cost, time.' },
          { q: '"Value-based pricing" means charging for…', options: ['The result/value you provide', 'Only hours', 'The cheapest rate', 'Nothing'], correct: 0, why: 'Charge for the value delivered.' },
          { q: 'If clients always say you\'re "too cheap," you may be…', options: ['Underpricing', 'Overpricing', 'Fair', 'Done'], correct: 0, why: 'That signals room to raise prices.' },
          { q: 'Clear scope prevents…', options: ['Doing unpaid extra work', 'Getting paid', 'Finishing', 'Pricing'], correct: 0, why: 'Scope stops unpaid extras.' },
          { q: 'Raising prices as your skill grows is…', options: ['Reasonable', 'Greedy always', 'Illegal', 'Pointless'], correct: 0, why: 'Better skill earns higher rates.' },
        ],
      },
      {
        title: 'Managing irregular income',
        body: [
          'With variable income, base your budget on your average or a conservative (low) month, not your best month.',
          'In high-earning months, save the surplus to cover low months — smooth your income yourself.',
          'Keep a larger emergency buffer than salaried people, since gaps are common.',
          'Pay essential bills and savings first when money arrives; treat extras as flexible.',
        ],
        quiz: [
          { q: 'With irregular income, budget based on…', options: ['A conservative/low month', 'Your best month', 'Zero', 'Borrowed money'], correct: 0, why: 'Plan around a low month.' },
          { q: 'In high-earning months you should…', options: ['Save the surplus for low months', 'Spend it all', 'Borrow more', 'Stop working'], correct: 0, why: 'Bank the surplus.' },
          { q: 'Irregular earners need an emergency buffer that is…', options: ['Larger than usual', 'Tiny', 'Zero', 'Negative'], correct: 0, why: 'Bigger buffer covers gaps.' },
          { q: 'When money arrives, pay first…', options: ['Essential bills and savings', 'Only luxuries', 'Friends', 'Nothing'], correct: 0, why: 'Cover essentials and savings first.' },
          { q: '"Smoothing" income means…', options: ['Saving peaks to cover dips', 'Spending peaks fast', 'Ignoring dips', 'Borrowing always'], correct: 0, why: 'Use good months to fund bad ones.' },
          { q: 'Basing your lifestyle on your best month is…', options: ['Risky', 'Smart', 'Required', 'Free'], correct: 0, why: 'Best months aren\'t guaranteed.' },
          { q: 'Surplus from a good month is best…', options: ['Saved for lean times', 'Spent immediately', 'Lent out', 'Ignored'], correct: 0, why: 'Save it for slow periods.' },
          { q: 'A bigger buffer helps because gaps are…', options: ['Common with gig income', 'Impossible', 'Rare', 'Illegal'], correct: 0, why: 'Income gaps happen often.' },
          { q: 'Flexible "extras" should be paid…', options: ['After essentials and savings', 'First', 'Never', 'With loans'], correct: 0, why: 'Extras come last.' },
          { q: 'Managing irregular income well requires…', options: ['Discipline and saving in good months', 'Luck only', 'Spending fast', 'Nothing'], correct: 0, why: 'Discipline smooths the ups and downs.' },
        ],
      },
    ],
  },
  {
    key: 'investing',
    title: 'Investing Basics for Beginners',
    icon: 'trending-up',
    blurb: 'Start investing wisely and spot scams.',
    lectures: [
      {
        title: 'What is investing vs saving',
        body: [
          'Saving is setting money aside safely for short-term needs; investing puts money to work to grow over the long term.',
          'Investments (DPS, FDR, stocks, mutual funds) can earn more than savings but carry some risk.',
          'Generally, higher potential return means higher risk — there is no safe way to get rich quickly.',
          "Invest only money you won't need soon, after building an emergency fund and clearing high-interest debt.",
        ],
        quiz: [
          { q: 'Saving is mainly for…', options: ['Short-term needs, kept safe', 'Long-term growth only', 'Gambling', 'Spending'], correct: 0, why: 'Saving keeps money safe and ready.' },
          { q: 'Investing aims to…', options: ['Grow money over the long term', 'Keep money idle', 'Lose money', 'Avoid returns'], correct: 0, why: 'It grows wealth over time.' },
          { q: 'Higher potential return usually means…', options: ['Higher risk', 'No risk', 'Lower risk', 'Guaranteed profit'], correct: 0, why: 'Return and risk move together.' },
          { q: 'You should invest money you…', options: ["Won't need soon", 'Need tomorrow', 'Borrowed', "Don't have"], correct: 0, why: 'Only invest spare, long-term money.' },
          { q: 'Before investing, you should first…', options: ['Build an emergency fund & clear costly debt', 'Spend savings', 'Borrow', 'Quit your job'], correct: 0, why: 'Secure the basics first.' },
          { q: 'Examples of investments include…', options: ['DPS, FDR, stocks, mutual funds', 'Only cash', 'Only bazar', 'None'], correct: 0, why: 'These put money to work.' },
          { q: '"Get rich quick with no risk" is…', options: ['Usually false', 'Always true', 'A safe plan', 'Recommended'], correct: 0, why: 'No risk-free fast riches exist.' },
          { q: 'Compared to saving, investing has…', options: ['More risk and more growth potential', 'Less of both', 'No difference', 'No risk'], correct: 0, why: 'More upside, more risk.' },
          { q: 'A good rule is to invest…', options: ['For the long term', "For tomorrow's rent", 'Your emergency fund', 'Borrowed money'], correct: 0, why: 'Investing rewards patience.' },
          { q: 'Risk in investing means…', options: ['Value can go up or down', 'Guaranteed loss', 'Guaranteed gain', 'Nothing'], correct: 0, why: 'Values fluctuate either way.' },
        ],
      },
      {
        title: 'DPS and fixed deposits explained',
        body: [
          'A DPS (Deposit Pension Scheme) is a bank plan where you deposit a fixed sum monthly for a set term and earn interest.',
          'A Fixed Deposit (FDR) locks a lump sum for a chosen term at a fixed interest rate; withdrawing early usually reduces returns.',
          'Both are low-risk and good for steady, predictable growth compared to keeping idle cash.',
          "Longer terms usually offer higher rates; match the term to when you'll need the money.",
        ],
        quiz: [
          { q: 'A DPS requires…', options: ['Fixed monthly deposits for a term', 'One lump sum only', 'No deposits', 'Daily withdrawals'], correct: 0, why: 'You deposit monthly for a term.' },
          { q: 'An FDR locks…', options: ['A lump sum for a fixed term', 'Monthly small sums', 'Your wallet', 'Nothing'], correct: 0, why: 'A lump sum is tied up for a term.' },
          { q: 'DPS and FDR are generally…', options: ['Low-risk', 'High-risk', 'Illegal', 'Free money'], correct: 0, why: 'Both are low-risk products.' },
          { q: 'Withdrawing an FDR early usually…', options: ['Reduces your returns', 'Boosts returns', 'Adds a bonus', 'Does nothing'], correct: 0, why: 'Early breaking cuts interest.' },
          { q: 'Longer terms usually offer…', options: ['Higher interest rates', 'Lower rates', 'No interest', 'Losses'], correct: 0, why: 'Longer locks pay more.' },
          { q: 'Compared to idle cash, DPS/FDR offer…', options: ['Steady growth', 'Less safety', 'No benefit', 'Higher risk only'], correct: 0, why: 'They beat cash sitting idle.' },
          { q: 'DPS is good for people who want…', options: ['Disciplined monthly saving with interest', 'Quick gambling', 'Daily spending', 'Loans'], correct: 0, why: 'It enforces steady saving.' },
          { q: 'You should match the deposit term to…', options: ["When you'll need the money", 'A random date', 'Forever', 'Never'], correct: 0, why: 'Align the term with your need.' },
          { q: '"FDR" is a…', options: ['Fixed Deposit Receipt', 'Free Daily Refund', 'Fund Distribution Rate', 'Foreign Debt Record'], correct: 0, why: 'Fixed Deposit Receipt.' },
          { q: 'A predictable, low-risk option is…', options: ['DPS or FDR', 'Risky stocks', 'A scam scheme', 'Lottery'], correct: 0, why: 'DPS/FDR are predictable.' },
        ],
      },
      {
        title: 'Intro to the Dhaka Stock Exchange',
        body: [
          'The Dhaka Stock Exchange (DSE) is where shares of listed companies are bought and sold.',
          'Buying a share makes you a part-owner; you can gain from price rises and dividends, but prices can also fall.',
          'To trade, you open a BO (Beneficiary Owner) account through a licensed broker.',
          "Stocks are higher-risk; learn the basics, diversify, and never invest money you can't afford to lose.",
        ],
        quiz: [
          { q: 'The DSE is where you…', options: ['Buy and sell company shares', 'Pay bills', 'Store cash', 'Get a loan'], correct: 0, why: 'It is a share marketplace.' },
          { q: 'Buying a share makes you…', options: ['A part-owner of the company', 'A lender', 'An employee', 'A customer only'], correct: 0, why: 'Shareholders own a slice.' },
          { q: 'To trade stocks, you need a…', options: ['BO account via a broker', 'SIM card', 'Passport only', 'Nothing'], correct: 0, why: 'A BO account is required.' },
          { q: 'Share prices can…', options: ['Rise or fall', 'Only rise', 'Only fall', 'Never change'], correct: 0, why: 'Prices move both ways.' },
          { q: '"BO account" stands for…', options: ['Beneficiary Owner account', 'Bank Online account', 'Big Order account', 'Buy Only account'], correct: 0, why: 'Beneficiary Owner account.' },
          { q: 'Stocks are generally…', options: ['Higher-risk', 'Risk-free', 'Guaranteed', 'Illegal'], correct: 0, why: 'Equities carry more risk.' },
          { q: 'Diversifying means…', options: ['Spreading money across investments', 'Buying one stock only', 'Avoiding all stocks', 'Borrowing'], correct: 0, why: 'Spread risk across holdings.' },
          { q: 'A dividend is…', options: ['A share of company profit paid to owners', 'A loan', 'A fee', 'A tax'], correct: 0, why: 'Profit paid to shareholders.' },
          { q: 'You should invest in stocks only…', options: ['Money you can afford to lose', 'Your rent money', 'Borrowed funds', 'Your emergency fund'], correct: 0, why: 'Never risk essential money.' },
          { q: 'Before buying stocks, you should…', options: ['Learn the basics', 'Guess randomly', 'Follow rumors', 'Borrow heavily'], correct: 0, why: 'Understand before you invest.' },
        ],
      },
      {
        title: 'Recognizing investment scams',
        body: [
          '"Guaranteed high returns with no risk" is the biggest red flag — real investments never guarantee profit.',
          'Be wary of schemes that pressure you to join fast, recruit others, or promise doubling your money quickly.',
          "Ponzi and MLM schemes pay early members with new members' money and eventually collapse.",
          'Check that any company is licensed (e.g., by BSEC) and never invest based on social media hype or "secret tips".',
        ],
        quiz: [
          { q: 'The biggest scam red flag is…', options: ['Guaranteed high returns, no risk', 'Some risk disclosed', 'A licensed firm', 'Slow growth'], correct: 0, why: 'No-risk guarantees are fake.' },
          { q: 'Real investments…', options: ['Never guarantee profit', 'Always guarantee profit', 'Have no risk', 'Double money weekly'], correct: 0, why: 'Profit is never guaranteed.' },
          { q: 'Pressure to "join fast" usually signals…', options: ['A scam', 'A good deal', 'Safety', 'Regulation'], correct: 0, why: 'Urgency is a scam tactic.' },
          { q: 'A Ponzi scheme pays old members with…', options: ["New members' money", 'Real profits', 'Bank interest', 'Government funds'], correct: 0, why: 'It just shuffles new money.' },
          { q: 'Schemes that rely on recruiting others are often…', options: ['MLM/pyramid scams', 'Safe investments', 'Bank products', 'Tax plans'], correct: 0, why: 'Recruitment-based = pyramid risk.' },
          { q: 'Before investing, check the company is…', options: ['Licensed (e.g., by BSEC)', 'Popular online', 'Recommended by a stranger', 'Secret'], correct: 0, why: 'Verify regulation/licensing.' },
          { q: '"Double your money in a week" is…', options: ['A classic scam', 'Realistic', 'Guaranteed', 'Safe'], correct: 0, why: 'Such promises are scams.' },
          { q: 'Investment "secret tips" on social media are…', options: ['Often unreliable or scams', 'Always true', 'Regulated', 'Safe bets'], correct: 0, why: 'Hype tips are risky.' },
          { q: 'Ponzi/MLM schemes eventually…', options: ['Collapse', 'Pay forever', 'Become banks', 'Are safe'], correct: 0, why: 'They run out of new money.' },
          { q: 'The safest approach to a "too good to be true" offer is…', options: ['Avoid it and verify', 'Invest fast', 'Recruit friends', 'Borrow to join'], correct: 0, why: 'Avoid and verify independently.' },
        ],
      },
    ],
  },
];
